# Generated by Django 5.0.1 on 2024-03-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_rename_mobile_number_service_mobilenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contactnumber', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('image', models.FileField(default=None, max_length=250, null=True, upload_to='services/')),
            ],
        ),
        migrations.DeleteModel(
            name='service',
        ),
    ]
